# Generated by Django 5.2.8 on 2025-11-11 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('3a3763c6-17b1-4fa3-b463-9aa5cb69b43f'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('4161296e-dbdc-4af1-890a-e37575f3599b'), max_length=255, null=True, unique=True),
        ),
    ]
