# Generated by Django 5.2.8 on 2025-11-13 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('4b94cb79-c486-45c4-89ca-907edca459c6'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('29363735-5b5b-47a7-98c0-1ad052d87f32'), max_length=255, null=True, unique=True),
        ),
    ]
