# Generated by Django 5.2.8 on 2025-11-17 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('8130b080-d822-43eb-8678-c1729299f5e1'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('30db8659-0bbb-46af-8ed4-dea9acd85792'), max_length=255, null=True, unique=True),
        ),
    ]
