# Generated by Django 5.2.8 on 2025-11-19 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('be17c010-a150-4e55-afbf-4a02622ce976'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('4b79d190-0cfe-4288-b4b8-ae7d261a2405'), max_length=255, null=True, unique=True),
        ),
    ]
