# Generated by Django 5.2.8 on 2025-11-19 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('72731dcd-9db6-41f3-99e1-c7973c07d88f'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('991a4e40-97df-4810-a72b-a22bfcf15aba'), max_length=255, null=True, unique=True),
        ),
    ]
