# Generated by Django 6.0.1 on 2026-01-20 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('fda90605-b7b2-47ba-9a34-acec9b2b6b63'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('1f680e35-15ec-4309-9ac3-b9f764c0c453'), max_length=255, null=True, unique=True),
        ),
    ]
