# Generated by Django 6.0.1 on 2026-01-20 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('470f2678-2a51-42fa-99a6-2906f955789b'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('50b1db1e-dbdd-4870-97f4-e5de24f72240'), max_length=255, null=True, unique=True),
        ),
    ]
