# Generated by Django 6.0.1 on 2026-01-20 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('87f681a8-ba8b-4142-b614-4861331dd2c6'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('00431f58-5666-4848-bf06-c1530d114111'), max_length=255, null=True, unique=True),
        ),
    ]
