# Generated by Django 6.0.1 on 2026-01-26 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('ab4a7389-b864-4f51-9d0c-d9b46123f2ed'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('f33daf26-4c85-44a4-9f8d-b5323a264090'), max_length=255, null=True, unique=True),
        ),
    ]
