# Generated by Django 6.0.1 on 2026-01-26 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('d7ca2ffc-4e94-48fb-b1fc-682a4b6331a6'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('6fd6b039-a9b0-4143-b023-99b9e67a1e58'), max_length=255, null=True, unique=True),
        ),
    ]
