# Generated by Django 6.0.1 on 2026-01-27 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('4521e6e0-aa0d-45b8-b171-330da01df1fc'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('95682a45-f977-4775-a2d1-d7ccab80cb72'), max_length=255, null=True, unique=True),
        ),
    ]
