# Generated by Django 6.0.1 on 2026-01-27 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('f81bf9f8-2aed-4e92-b9b7-f71d1497807a'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('c798ed64-1164-4397-a991-16a3a8a31919'), max_length=255, null=True, unique=True),
        ),
    ]
