# Generated by Django 6.0.1 on 2026-01-27 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('445da766-2105-469f-b977-8b17a8c12618'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('b8afc8a5-d4f3-4dc0-b05d-998616a0c441'), max_length=255, null=True, unique=True),
        ),
    ]
