# Generated by Django 6.0.1 on 2026-02-24 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('dda40bda-bd3a-46f8-a4d0-885c6fcac17f'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('0aee1494-7136-4040-95f5-c08f05a5a178'), max_length=255, null=True, unique=True),
        ),
    ]
