# Generated by Django 6.0.1 on 2026-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_profile_current_left_pv_profile_current_right_pv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_left_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_right_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
