# Generated by Django 6.0.1 on 2026-01-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_profile_total_left_count_profile_total_right_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/pan/'),
        ),
    ]
