# Generated by Django 6.0.1 on 2026-01-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_transaction_tds_amount_transaction_top_up_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('purchase', 'Purchase'), ('binary_income', 'Binary Income'), ('level_income', 'Level Income'), ('referral_bonus', 'Referral Bonus'), ('tds', 'TDS'), ('top_up', 'Top-Up')], max_length=20),
        ),
    ]
