# Generated by Django 6.0.1 on 2026-02-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/banner/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('purchase', 'Purchase'), ('binary_income', 'Binary Income'), ('level_income', 'Level Income'), ('referral_bonus', 'Referral Bonus'), ('tds', 'TDS'), ('top_up', 'Top-Up'), ('pin_purchase', 'Pin Purchase')], max_length=20),
        ),
    ]
