# Generated by Django 6.0.1 on 2026-03-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_category_banner_image_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kyc',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='passbook_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/passbooks/'),
        ),
    ]
